import ShoppingBasketIcon from "@mui/icons-material/ShoppingBasket";
import FavoriteBorderIcon from "@mui/icons-material/FavoriteBorder";
export const Cart = {
  productCart: [
    {
      price: 670,
      title: "Product name 123",
      img: "/assets/top-rated.png",
      id: 1,
      quantity: 1,
    },
    {
      price: 100,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 2,
      quantity: 1,
    },
    {
      price: 200,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 3,
      quantity: 1,
    },
    {
      price: 300,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 4,
      quantity: 1,
    },
    {
      price: 400,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 5,
      quantity: 1,
    },
    {
      price: 500,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 6,
      quantity: 1,
    },
    {
      price: 600,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 7,
      quantity: 1,
    },
    {
      price: 700,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 8,
      quantity: 1,
    },
    {
      price: 800,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 9,
      quantity: 1,
    },
    {
      price: 900,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 10,
      quantity: 1,
    },
    {
      price: 150,
      img: "/assets/top-rated.png",
      title: "Product name 123",
      id: 11,
      quantity: 1,
    },
  ],
};

export const Brands = {
  productBrands: [
    {
      price: 670,
      title: "Brand name 123",
      img: "/assets/top-rated.png",
      id: 1,
    },
    {
      price: 100,
      img: "/assets/top-rated.png",
      title: "Brand name 123",
      id: 2,
    },
    {
      price: 200,
      img: "/assets/top-rated.png",
      title: "Brand name 123",
      id: 3,
    },
    {
      price: 300,
      img: "/assets/top-rated.png",
      title: "Brand name 123",
      id: 4,
    },
    {
      price: 400,
      img: "/assets/top-rated.png",
      title: "Brand name 123",
      id: 5,
    },
    {
      price: 500,
      img: "/assets/top-rated.png",
      title: "Brand name 123",
      id: 6,
    },
  ],
};

export const Range = {
  productRanges: [
    {
      price: 670,
      title: "Red",
      description: "X products",
      img: "/assets/red-wine.png",
      id: 1,
    },
    {
      price: 100,
      img: "/assets/white-wine.png",
      title: "White",
      description: "X products",
      id: 2,
    },
    {
      price: 200,
      img: "/assets/rose-wine.png",
      title: "Rose",
      description: "X products",
      id: 3,
    },
    {
      price: 300,
      img: "/assets/sparkling-wine.png",
      title: "Sparkling",
      description: "X products",
      id: 4,
    },
    {
      price: 300,
      img: "/assets/sparkling-wine.png",
      title: "Sparkling",
      description: "X products",
      id: 5,
    },
    {
      price: 300,
      img: "/assets/sparkling-wine.png",
      title: "Sparkling",
      description: "X products",
      id: 6,
    },
  ],
};

export const LoginData = {
  dummyLoginData: [
    {
      email: "john@example.com",
      password: "pass123",
    },
    {
      email: "jane@example.com",
      password: "Strongpass456",
    },
    {
      email: "alice@example.com",
      password: "safepass789",
    },
    // Add more dummy data entries as needed
  ],
};

// Buyer

export const buyers = [
  {
    name: "nikit",
    email: "nikitkumawat@gmail.com",
    BusinessName: "hgh",
    ABN: "00000000000",
    LiquerLicence: "bnvnhhgyu",
    DeliveryAddress: "nbj",
    Apartment: "hgfgjfh",
    Suburb: "kjhgkjh",
    Postcode: "0000",
    Notes: "jgyu",
    DeliveryAddressState: "chocolate",
    FirstName: "Nikit",
    LastName: "Kumawat",
    Mobile: "+919057221504",
    OrderContactState: "chocolate",
    OrderingContactFirstName: "hfhgfh",
    OrderingContactLastName: "jgughj",
    OrderingContactEmail: "nikitkumawat@gmail.com",
    OrderingContactMobile: "+919057221504",
    DeliveryContactFirstName: "ygygu",
    DeliveryContactLastName: "iuyugli",
    DeliveryContactEmail: "hjfkhj",
    DeliveryContactMobile: "+919057221504",
  },
  {
    name: "nikit1",
    email: "nikitkumawat1@gmail.com",
    password: "nikit@12345",
    BusinessName: "hgh",
    ABN: "0000000000",
    LiquerLicence: "bnvnh",
    DeliveryAddress: "nbj",
    Apartment: "hgfgjfh",
    Suburb: "kjhgkjh",
    Postcode: "0000",
    Notes: "jgyu",
    DeliveryAddressState: "chocolate",
    FirstName: "Nikit1",
    LastName: "Kumawat",
    Mobile: "+919057221504",
    OrderContactState: "chocolate",
    OrderingContactFirstName: "hfhgfh",
    OrderingContactLastName: "jgughj",
    OrderingContactEmail: "nikitkumawat1@gmail.com",
    OrderingContactMobile: "+919057221504",
    DeliveryContactFirstName: "ygygu",
    DeliveryContactLastName: "iuyugli",
    DeliveryContactEmail: "hjfkhj",
    DeliveryContactMobile: "+919057221504",
  },
  {
    name: "Ragahv Saini",
    email: "raghavsaini30795@gmail.com",
    password: "Raghav@1849",
    BusinessName: "hgh",
    ABN: "00000000000",
    LiquerLicence: "bnvnh",
    DeliveryAddress: "nbj",
    Apartment: "hgfgjfh",
    Suburb: "kjhgkjh",
    Postcode: "0000",
    Notes: "jgyu",
    DeliveryAddressState: "chocolate",
    FirstName: "Nikit1",
    LastName: "Kumawat",
    Mobile: "+61(02)89876544",
    OrderContactState: "chocolate",
    OrderingContactFirstName: "hfhgfh",
    OrderingContactLastName: "jgughj",
    OrderingContactEmail: "raghavsaini30795@gmail.com",
    OrderingContactMobile: "+61289876544",
    DeliveryContactFirstName: "ygygu",
    DeliveryContactLastName: "iuyugli",
    DeliveryContactEmail: "raghavsaini30795@gmail.com",
    DeliveryContactMobile: "0414 570 776",
  },
];

export const options = [
  { value: "chocolate", label: "Chocolate" },
  { value: "strawberry", label: "Strawberry" },
  { value: "vanilla", label: "Vanilla" },
];

export const listdata = [
  {
    id: 1,
    img: "/assets/product.png",
    title: "Write Product Full Name1",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: " $25.08",
  },
  {
    id: 2,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 3,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 4,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 5,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 6,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 7,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 8,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
  {
    id: 9,
    img: "/assets/product.png",
    title: "Write Product Full Name",
    name: " Brand name",
    details: "12 bottle case (750ml)",
    price: "$25.08",
  },
];
