export const setBuyerValues = (buyer, dispatch, updateField) => {
  console.log("buyer", buyer);
  dispatch(
    updateField({
      name: buyer?.businessName,
      email: buyer?.deliveryEmail,
      password: "",
      brn: buyer?.brn,
      cbrn: buyer?.cbrn,
      businessName: buyer?.businessName,
      abn: buyer?.abn,
      liquorLicence: buyer?.liquorLicence,
      deliveryAddress: buyer?.address,
      apartment: buyer?.apartment,
      suburb: buyer?.suburb,
      postcode: buyer?.postalCode,
      notes: buyer?.deliveryNotes,
      deliveryAddressState: buyer?.state,
      firstName: buyer?.deliveryFirstName,
      lastName: buyer?.deliveryLastName,
      mobile: buyer?.mobile,
      organisationId: buyer?.organisationId,
      orderContactState: buyer?.orderingState,
      orderingContactFirstName: buyer?.orderingFirstName,
      orderingContactLastName: buyer?.orderingLastName,
      orderingContactEmail: buyer?.orderingEmail,
      orderingContactMobile: buyer?.orderingMobile,
      deliveryContactFirstName: buyer?.deliveryFirstName,
      deliveryContactLastName: buyer?.deliveryLastName,
      deliveryContactEmail: buyer?.deliveryEmail,
      deliveryContactMobile: buyer?.deliveryMobile,
      billingContactAddress: buyer?.billingAddress,
      billingContactApartment: buyer?.billingApartment,
      billingContactPostalCode: buyer?.billingPostalCode,
      billingContactState: buyer?.billingState,
      billingContactSuburb: buyer?.billingSuburb,
    })
  );

  //   return {
  //     name: buyer?.businessName,
  //     email: buyer?.deliveryEmail,
  //     password: "",
  //     brn: buyer?.brn,
  //     cbrn: buyer?.cbrn,
  //     businessName: buyer?.businessName,
  //     abn: buyer?.abn,
  //     liquorLicence: buyer?.liquorLicence,
  //     deliveryAddress: buyer?.address,
  //     apartment: buyer?.apartment,
  //     suburb: buyer?.suburb,
  //     postcode: buyer?.postalCode,
  //     notes: buyer?.deliveryNotes,
  //     deliveryAddressState: buyer?.state,
  //     firstName: buyer?.deliveryFirstName,
  //     lastName: buyer?.deliveryLastName,
  //     mobile: buyer?.mobile,
  //     organisationId: buyer?.organisationId,
  //     orderContactState: buyer?.orderingState,
  //     orderingContactFirstName: buyer?.orderingFirstName,
  //     orderingContactLastName: buyer?.orderingLastName,
  //     orderingContactEmail: buyer?.orderingEmail,
  //     orderingContactMobile: buyer?.orderingMobile,
  //     deliveryContactFirstName: buyer?.deliveryFirstName,
  //     deliveryContactLastName: buyer?.deliveryLastName,
  //     deliveryContactEmail: buyer?.deliveryEmail,
  //     deliveryContactMobile: buyer?.deliveryMobile,
  //   };
};
