import * as Yup from "yup";

export const addProductSchema = Yup.object().shape({
    status: Yup.string(),
  visibility: Yup.boolean(),
  region: Yup.array(),
  minimumOrder: Yup.string(),
  trackInventory: Yup.boolean(),
  stockAlertLevel: Yup.string(),
  sellOutOfStock: Yup.boolean(),
  title: Yup.string(),
  skuCode: Yup.string(),
  brand: Yup.string(),
  department: Yup.string(),
  category: Yup.string(),
  subcategory: Yup.string(),
  segment: Yup.string(),
  grapeVariety: Yup.array(),
  regionSelect: Yup.string(),
  vintage: Yup.string(),
  awards: Yup.string(),
  abv: Yup.string(),
  country: Yup.string(),
  baseUnitMeasure: Yup.string(),
  innerUnitMeasure: Yup.string(),
  configuration: Yup.string(),
  description: Yup.string(),
  tags: Yup.array(),
  salePrice: Yup.string(),
  buyPrice: Yup.string(),
  profit: Yup.string(),
  margin: Yup.string(),
  tax: Yup.string(),
  wineEqualisationTax: Yup.string(),
  landedUnitCost: Yup.string(),
})